dspPoolSize: 6
chnlzrHostname: localhost
chnlzrPort: 8080
channelRequestTimeoutMs: 2000
channelQualifyTimeMs: 8000
samplesQueueSize: 10
minDataUnitRate: 0.5
controlChannelRetryCount: 2
controlChannelRetryDelayMs: 5000

server:
  type: simple
  applicationContextPath: /
  connector:
    type: http
    port: 8080

kinesis:
  region: us-west-2
  streamName: idk-stream
  accessKeyId: aaabbb111222
  secretKey: cccddd333444
  appName: p25dcodr
  appVersion: v0.3.0
  messageSizeMax: 512
  payloadsPerRecordMax: 1
  senderPoolSize: 6
  senderQueueSize: 48
  controlDelayMaxMs: 30000
  trafficDelayMaxMs: 30000

logging:
  level: INFO
  appenders:
    - type: console
      threshold: ALL
      timeZone: UTC
      target: stdout
