dspPoolSize: 6
brkrHostname: localhost
brkrPort: 9090
channelRequestTimeoutMs: 4000
channelQualifyTimeMs: 8000
minDataUnitRate: 1.0
controlChannelRetryCount: 2
controlChannelRetryDelayMs: 5000

server:
  type: simple
  applicationContextPath: /
  connector:
    type: http
    port: 7070

kinesis:
  region: us-west-2
  streamName: idk-stream
  accessKeyId: aaabbb111222
  secretKey: cccddd333444
  appName: p25dcodr
  appVersion: v0.1
  messageSizeMax: 2048
  payloadsPerRecordMax: 1
  senderPoolSize: 6
  senderQueueSize: 10
  controlDelayMaxMs: 30000
  trafficDelayMaxMs: 30000

logging:
  level: INFO
  appenders:
    - type: console
      threshold: ALL
      timeZone: UTC
      target: stdout
