dspPoolSize: 8
brkrHostname: localhost
brkrPort: 9090
channelRequestTimeoutMs: 4000
channelQualifyTimeMs: 8000
minDataUnitRate: 1.0
controlChannelRetryCount: 2
controlChannelRetryDelayMs: 5000

server:
  type: simple
  applicationContextPath: /
  connector:
    type: http
    port: 7070

logging:
  level: INFO
  appenders:
    - type: console
      threshold: ALL
      timeZone: UTC
      target: stdout
